name: 构建与发布

on:
  push:
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      # 为macOS设置适当的Python环境
      - name: 设置Python环境（macOS）
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 在macOS上安装必要的Python依赖
      - name: 安装Python依赖（macOS）
        if: matrix.os == 'macos-latest'
        run: |
          pip install setuptools

      - name: 构建应用
        run: npm run build

      - name: 构建并发布应用 (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # 首先构建 x64 版本
          npm run build:mac
          # 然后构建 arm64 版本 (可选，取决于是否需要支持 Apple Silicon)
          # npm run build:mac -- --arm64
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: 构建并发布应用 (Windows)
        if: matrix.os == 'windows-latest'
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
